# Generated by Django 3.0.4 on 2020-03-17 18:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20200317_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 17, 18, 8, 59, 972499, tzinfo=utc)),
        ),
    ]
