# Generated by Django 3.0.4 on 2020-03-17 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20200317_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
