# Generated by Django 3.0.4 on 2020-04-05 21:44

from django.db import migrations, models, transaction
from ..models import Post, User


def create_initial_data(apps, schema_editor):
    try:
        Post(title="My Second Post", place="Hatay", note= "hatay çok guzel bir yer", created_by = 1).save()
        Post(title="My Third Post", place="Hatay", note= "hatay çok guzel bir yer", created_by = 2).save()
        Post(title="My Third Post", place="Hatay", note= "hatay çok guzel bir yer", created_by = 2).save()
            

    except:
        print("Sağlık olsun")

class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_post_title'),
    ]

    operations = [
  	  	migrations.RunPython(create_initial_data),
    ]
