# Generated by Django 3.0.4 on 2020-04-05 21:44

from django.db import migrations
from django.contrib.auth.models import User
from django.utils import timezone
from ..models import Post


def create_initial_data(apps, schema_editor):
  
    # Post = apps.get_model('agenda', 'Post')
    us1 = User.objects.create_superuser(username="bilginyuksel", password="bilginyuksel",is_staff = True, is_superuser = True, last_login=str(timezone.now()))
    us2 = User.objects.create_superuser(username='kartaca', password="kartaca", is_staff = True, is_superuser = True, last_login=str(timezone.now()))

    Post(title="Best travel", note="Best travel note", place="Singapore", created_by=us1).save()
    Post(title="You should see it", note="You should see it note", place="New York", created_by=us2).save()
    Post(title="My experiences", note="My Experirences note", place="Washington DC", created_by=us1).save()
    Post(title="Awesome !", note="Awesome note", place="Netherlands", created_by=us2).save()
    Post(title="Rainy Day", note="Rainy Day note", place="Turkey", created_by=us2).save()
    Post(title="Close to Sun", note="Close to sun note", place="Mars", created_by=us1).save()
    Post(title="Deep thoughts", note="deep thougts note", place="Pluton", created_by=us1).save()
    Post(title="Life!", note="life note", place="Bahama Island", created_by=us2).save()
    Post(title="Let's fun", note="let's fun note.", place="Ibiza", created_by=us1).save()




class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_post_title'),
    ]

    operations = [
  	  	migrations.RunPython(create_initial_data),
    ]
